version: "3"
services:
  mysql01:
    image: mysql:5.7.32
    networks:
      - redminenet
    volumes:
      - mysqlVol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass 
      MYSQL_DATABASE: redmine1111 
      MYSQL_USER: redmineuser 
      MYSQL_PASSWORD: useradmin 
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    
  redmine:
    depends_on:
      - mysql01
    image: redmine:4.2.3-alpine
    networks:
      - redminenet
    volumes:
      - redmineVol:/usr/src/redmine/files
      - redmineVol:/usr/src/redmine/public/themes
      - redmineVol:/usr/src/redmine/plugins
    ports:
      - 8086:3000
    restart: always
    environment:
      REDMINE_DB_MYSQL: mysql01
      REDMINE_DB_DATABASE: redmine1111
      REDMINE_DB_USERNAME: redmineuser
      REDMINE_DB_PASSWORD: useradmin

networks:
  redminenet:
volumes:
  mysqlVol:
  redmineVol:
